wandb_version: 1

env_name:
  desc: null
  value: MountainCarContinuous-v0
max_num_episodes:
  desc: null
  value: 100000
learning_rate:
  desc: null
  value: 0.0005
gamma:
  desc: null
  value: 0.97
print_episode_interval:
  desc: null
  value: 20
train_num_episodes_before_next_test:
  desc: null
  value: 50
validation_num_episodes:
  desc: null
  value: 5
episode_reward_avg_solved:
  desc: null
  value: 85
epsilon_start:
  desc: null
  value: 0.5
epsilon_end:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717137490
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
